adjective = input ('Введите прилагательное: ')
noun = input ('Введите существительное: ')
verb = input ('Введите глагол в прошедшем времени: ')
animal = input ('Ввидите животное: ')
linin = input ('Характеристика животного: ')
print ('Ваша чепуха')
print ('Этот', adjective, noun, verb, 'на ленивую', linin, animal. )